// Code generated by robots; DO NOT EDIT.

package avutil

import (
	common "github.com/ssttevee/go-av/internal/common"
	"unsafe"
)

/*
#include <libavutil/avutil.h>
#include <libavutil/buffer.h>
#include <libavutil/dict.h>
#include <libavutil/frame.h>
#include <libavutil/pixdesc.h>
#include <libavutil/hwcontext.h>
#include <libavutil/log.h>
#include <libavutil/opt.h>
*/
import "C"

type BufferRef struct {
	Buffer *C.struct_AVBuffer
	Data   *uint8
	Size   int32
	_      [4]byte
}
type Class struct {
	ClassName              *common.CChar
	ItemName               *[0]byte
	Option                 *Option
	Version                int32
	LogLevelOffsetOffset   int32
	ParentLogContextOffset int32
	ChildNext              *[0]byte
	ChildClassNext         *[0]byte
	Category               C.AVClassCategory
	GetCategory            *[0]byte
	QueryRanges            *[0]byte
}
type Frame struct {
	Data                 [8]*uint8
	Linesize             [8]int32
	ExtendedData         **uint8
	Width                int32
	Height               int32
	NbSamples            int32
	Format               int32
	KeyFrame             int32
	PictType             uint32
	SampleAspectRatio    Rational
	Pts                  int64
	PktPts               int64
	PktDts               int64
	CodedPictureNumber   int32
	DisplayPictureNumber int32
	Quality              int32
	Opaque               unsafe.Pointer
	Error                [8]uint64
	RepeatPict           int32
	InterlacedFrame      int32
	TopFieldFirst        int32
	PaletteHasChanged    int32
	ReorderedOpaque      int64
	SampleRate           int32
	ChannelLayout        uint64
	Buf                  [8]*BufferRef
	ExtendedBuf          **BufferRef
	NbExtendedBuf        int32
	SideData             **FrameSideData
	NbSideData           int32
	Flags                int32
	ColorRange           uint32
	ColorPrimaries       uint32
	ColorTrc             uint32
	Colorspace           uint32
	ChromaLocation       uint32
	BestEffortTimestamp  int64
	PktPos               int64
	PktDuration          int64
	Metadata             *Dictionary
	DecodeErrorFlags     int32
	Channels             int32
	PktSize              int32
	QscaleTable          *int8
	Qstride              int32
	QscaleType           int32
	QpTableBuf           *BufferRef
	HwFramesCtx          *BufferRef
	OpaqueRef            *BufferRef
	CropTop              uint64
	CropBottom           uint64
	CropLeft             uint64
	CropRight            uint64
	PrivateRef           *BufferRef
}
type FrameSideData struct {
	Type     uint32
	Data     *uint8
	Size     int32
	Metadata *Dictionary
	Buf      *BufferRef
}
type HWDeviceContext struct {
	AvClass    *Class
	Internal   *C.struct_AVHWDeviceInternal
	Type       uint32
	Hwctx      unsafe.Pointer
	Free       *[0]byte
	UserOpaque unsafe.Pointer
}
type HWFramesContext struct {
	AvClass         *Class
	Internal        *C.struct_AVHWFramesInternal
	DeviceRef       *BufferRef
	DeviceCtx       *HWDeviceContext
	Hwctx           unsafe.Pointer
	Free            unsafe.Pointer
	UserOpaque      unsafe.Pointer
	Pool            *C.struct_AVBufferPool
	InitialPoolSize int32
	Format          PixelFormat
	SwFormat        PixelFormat
	Width           int32
	Height          int32
	_               [4]byte
}
type Option struct {
	Name       *common.CChar
	Help       *common.CChar
	Offset     int32
	Type       OptionType
	DefaultVal [8]byte
	Min        float64
	Max        float64
	Flags      int32
	Unit       *common.CChar
}
type Rational struct {
	Num int32
	Den int32
}
