// Code generated by robots; DO NOT EDIT.

package avformat

import (
	avcodec "github.com/ssttevee/go-av/avcodec"
	avutil "github.com/ssttevee/go-av/avutil"
	common "github.com/ssttevee/go-av/internal/common"
	"unsafe"
)

/*
#include <libavformat/avformat.h>
*/
import "C"

type Context struct {
	AvClass                     *avutil.Class
	Iformat                     *InputFormat
	Oformat                     *C.struct_AVOutputFormat
	PrivData                    unsafe.Pointer
	Pb                          *IOContext
	CtxFlags                    int32
	NbStreams                   uint32
	Streams                     **Stream
	NbStreamGroups              uint32
	StreamGroups                **C.struct_AVStreamGroup
	NbChapters                  uint32
	Chapters                    **C.struct_AVChapter
	Url                         *common.CChar
	StartTime                   int64
	Duration                    int64
	BitRate                     int64
	PacketSize                  uint32
	MaxDelay                    int32
	Flags                       int32
	Probesize                   int64
	MaxAnalyzeDuration          int64
	Key                         *uint8
	Keylen                      int32
	NbPrograms                  uint32
	Programs                    **C.struct_AVProgram
	VideoCodecID                uint32
	AudioCodecID                uint32
	SubtitleCodecID             uint32
	DataCodecID                 uint32
	Metadata                    *avutil.Dictionary
	StartTimeRealtime           int64
	FpsProbeSize                int32
	ErrorRecognition            int32
	InterruptCallback           C.struct_AVIOInterruptCB
	Debug                       int32
	MaxStreams                  int32
	MaxIndexSize                uint32
	MaxPictureBuffer            uint32
	MaxInterleaveDelta          int64
	MaxTsProbe                  int32
	MaxChunkDuration            int32
	MaxChunkSize                int32
	MaxProbePackets             int32
	StrictStdCompliance         int32
	EventFlags                  int32
	AvoidNegativeTs             int32
	AudioPreload                int32
	UseWallclockAsTimestamps    int32
	SkipEstimateDurationFromPts int32
	AvioFlags                   int32
	DurationEstimationMethod    uint32
	SkipInitialBytes            int64
	CorrectTsOverflow           uint32
	Seek2Any                    int32
	FlushPackets                int32
	ProbeScore                  int32
	FormatProbesize             int32
	CodecWhitelist              *common.CChar
	FormatWhitelist             *common.CChar
	ProtocolWhitelist           *common.CChar
	ProtocolBlacklist           *common.CChar
	IoRepositioned              int32
	VideoCodec                  *avcodec.Codec
	AudioCodec                  *avcodec.Codec
	SubtitleCodec               *avcodec.Codec
	DataCodec                   *avcodec.Codec
	MetadataHeaderPadding       int32
	Opaque                      unsafe.Pointer
	ControlMessageCb            C.av_format_control_message
	OutputTsOffset              int64
	DumpSeparator               *uint8
	IoOpen                      *[0]byte
	IoClose2                    *[0]byte
	DurationProbesize           int64
}
type IOContext struct {
	AvClass             *avutil.Class
	Buffer              *byte
	BufferSize          int32
	BufPtr              *byte
	BufEnd              *byte
	Opaque              unsafe.Pointer
	ReadPacket          *[0]byte
	WritePacket         *[0]byte
	Seek                *[0]byte
	Pos                 int64
	EofReached          int32
	Error               int32
	WriteFlag           int32
	MaxPacketSize       int32
	MinPacketSize       int32
	Checksum            C.ulong
	ChecksumPtr         *byte
	UpdateChecksum      *[0]byte
	ReadPause           *[0]byte
	ReadSeek            *[0]byte
	Seekable            int32
	Direct              int32
	ProtocolWhitelist   *common.CChar
	ProtocolBlacklist   *common.CChar
	WriteDataType       *[0]byte
	IgnoreBoundaryPoint int32
	BufPtrMax           *byte
	BytesRead           int64
	BytesWritten        int64
}
type InputFormat struct {
	Name       *common.CChar
	LongName   *common.CChar
	Flags      int32
	Extensions *common.CChar
	CodecTag   **C.struct_AVCodecTag
	PrivClass  *avutil.Class
	MimeType   *common.CChar
}
type Stream struct {
	AvClass           *avutil.Class
	Index             int32
	ID                int32
	Codecpar          *avcodec.Parameters
	PrivData          unsafe.Pointer
	TimeBase          avutil.Rational
	StartTime         int64
	Duration          int64
	NbFrames          int64
	Disposition       int32
	Discard           int32
	SampleAspectRatio avutil.Rational
	Metadata          *avutil.Dictionary
	AvgFrameRate      avutil.Rational
	AttachedPic       avcodec.Packet
	SideData          *C.struct_AVPacketSideData
	NbSideData        int32
	EventFlags        int32
	RFrameRate        avutil.Rational
	PtsWrapBits       int32
	_                 [4]byte
}
